var css= document.querySelector("h3");
var col1= document.querySelector(".color1");
var col2= document.querySelector(".color2");
var body=document.getElementById("grad");

//wrong code:it looks like we can't save a var which leads
//  to a style property at once
// var background=document.getElementById("grad").style.background;

// background="red";


//the right code: is to select only the element and save
//that in the var then use the var's style property as follow:

// var body=document.getElementById("grad");

// body.style.background="red";


function setGrad(){
	body.style.background=
	"linear-gradient(to right,"
	+col1.value
	+","
	+col2.value
	+")";
	css.textContent = body.style.background + ";";//I think
	//because textContent is designed to get its input from
	//paths in the css file and from the dom may be that's why
	//  it requires a semoicolon because in css file this
	//is the format (not sure at all about that 0% sure)
}
col1.addEventListener("input",
	// function(){
// 	body.style.background=
// 	"linear-gradient(to right,"
// 	+col1.value
// 	+","
// 	+col2.value
// 	// +");";  the value of body.style.background isn't the
// 	//innerHTML or the css value but it's the value stored
// 	//in the textNode of the body.style.background in the DOM
// 	//which is created or generated by the browser thus we don't
// 	//need to add a semicolon as we do in css because the values
// 	//of the textNodes in the DOM are saved in plain text (20%
// 	//  I think that is the case here)
// // 	+")";

// });
setGrad);
col2.addEventListener("input",setGrad);//comment this out
//and use oninput attribute in html instead
//notice that on input require the function to be called
//i.e setGrad() and not setGrad






















//my try:

// firstVal= col1.value;

// secondVal= col2.value;



// function h(e){
// 	console.log(e.target.value);
// 	if(e.target.name="color1")
// 		firstVal=e.target.value;
// 	if(e.target.name="color2")
// 		secondVal=e.target.value;
// 		background= "linear-gradient(to right,"+firstVal+","+secondVal+");";

// }

